server:
  port: 900

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Utilise Eureka pour découvrir les microservices
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/api/v1/schools/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Student Service
        url: /api/v1/students/v3/api-docs
      - name: School Service
        url: /api/v1/schools/v3/api-docs
      - name: Employee Service
        url: /api/v1/employees/v3/api-docs
