server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/schools/**
        - id: employee-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/employees/**
